### ISSUE TITLE
mac升级后不支持这个repo里的KindleGen版本了，附解决方案

### ISSUE THREAD

**Issue by verazuo** [renweizhukov/txt2mobi3#4]
这个repo里的kindlegen是32位的，mac升级到catalina之后就不支持运行32位的软件了，故报错：
```[INFO]: 章节HTML（标题=第82章, 索引=87）生成完毕
[INFO]: 章节HTML（标题=第83章, 索引=88）生成完毕
[INFO]: 章节HTML（标题=第84章, 索引=89）生成完毕
[INFO]: book-1.html文件生成完毕
[INFO]: 调用KindleGen："/Users/vera/Desktop/code/txt2mobi3/txt2mobi3/resources/kindlegen/mac/kindlegen" "/Users/vera/.txt2mobi3/project-1.opf"
sh: /Users/vera/Desktop/code/txt2mobi3/txt2mobi3/resources/kindlegen/mac/kindlegen: Bad CPU type in executable
Traceback (most recent call last):
  File "/Users/vera/anaconda3/envs/py36/lib/python3.6/shutil.py", line 550, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/vera/.txt2mobi3/project-1.mobi' -> '/Users/vera/Desktop/code/txt2mobi3/txt2mobi3/xxxxxx.mobi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vera/anaconda3/envs/py36/bin/txt2mobi3_clt", line 33, in <module>
    sys.exit(load_entry_point('txt2mobi3', 'console_scripts', 'txt2mobi3_clt')())
  File "/Users/vera/Desktop/code/txt2mobi3/txt2mobi3/txt2mobi3_clt.py", line 186, in txt2mobi3_clt
    Txt2Mobi3Clt()
  File "/Users/vera/Desktop/code/txt2mobi3/txt2mobi3/txt2mobi3_clt.py", line 39, in __init__
    getattr(self, args.command)()
  File "/Users/vera/Desktop/code/txt2mobi3/txt2mobi3/txt2mobi3_clt.py", line 141, in conv
    self._conv()
  File "/Users/vera/Desktop/code/txt2mobi3/txt2mobi3/txt2mobi3_clt.py", line 182, in _conv
    self._txt2mobi3.convert(is_dryrun, book_params)
  File "/Users/vera/Desktop/code/txt2mobi3/txt2mobi3/txt2mobi3.py", line 161, in convert
    shutil.move(src_path, des_path)
  File "/Users/vera/anaconda3/envs/py36/lib/python3.6/shutil.py", line 564, in move
    copy_function(src, real_dst)
  File "/Users/vera/anaconda3/envs/py36/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/vera/anaconda3/envs/py36/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/vera/.txt2mobi3/project-1.mobi'
```

**解决办法：**
将`txt2mobi3/resources/kindlegen/mac/kindlegen`替换为下面链接里提供的64位kindlegen。
https://bookfere.com/post/815.html

不想替换的也可以直接将`/.txt2mobi3/.config.ini`里的kindlegen配置路径改为64位的kindlegen的路径。

**Comment by renweizhukov** [comment]
谢谢@verazuo 提供详细的解决方案！我已经更新了kindlegen for Mac，在我本地的Macbook上测试kindlegen可以运行。

**Comment by renweizhukov** [comment]
对了，https://bookfere.com/post/815.html 上面用homebrew安装Kindle Previewer 3的命令有误，应该是：

```
$ brew install --cask kindle-previewer
```

**Comment by verazuo** [comment]
> 对了，https://bookfere.com/post/815.html 上面用homebrew安装Kindle Previewer 3的命令有误，应该是：
> 
> ```
> $ brew install --cask kindle-previewer
> ```

感谢回复和更新！
我本地测试是直接用的他给的64bit kindlegen，没有自己手动从kindle-previewer里提取 
能用就好:D ~
